// JsFromRoutes CacheKey b96e8a0ccc94e31a2f85b5f25d1909a2
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/users'),
  create: /* #__PURE__ */ definePathHelper('post', '/users'),
  new: /* #__PURE__ */ definePathHelper('get', '/users/new'),
}
