// JsFromRoutes CacheKey 48fbb8c567fd19a69b7d14c2fc67a61e
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  new: /* #__PURE__ */ definePathHelper('get', '/admin/users/new'),
  create: /* #__PURE__ */ definePathHelper('post', '/admin/users/create'),
}
