// JsFromRoutes CacheKey 271121bd7bb9d6b75b494aee72f6f058
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/admin/home/index'),
}
