// JsFromRoutes CacheKey 3edc06be1f86ad9198474cf7dd007add
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/admin/users'),
  create: /* #__PURE__ */ definePathHelper('post', '/admin/users'),
  new: /* #__PURE__ */ definePathHelper('get', '/admin/users/new'),
}
